spring:
  config:
    import: optional:application-secret.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/carrot
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000      # 30분 (ms)
  refresh-expiration: 604800000   # 7일 (ms)

aws:
  s3:
    bucket: carrot-265311921902-ap-northeast-2-an
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}